name: Windows Installer Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "CCON Version"
        required: true
        default: "1.0.0"
        type: string

jobs:
  win64_build:
    name: Build x64 Installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install upx
      - name: Build
        run: |
          cmake . -S. -B _build -A x64 -G "Visual Studio 16 2019"
          cmake --build _build --config Release
      - name: Compress Binaries
        run: |
          echo "Size:"
          echo ((Get-Item _build/Release/ccon.exe).length)
          upx -9 _build/Release/ccon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/Release/ccon.exe).length)
      - name: Build Installer
        run: |
          makensis -D VERSION="${{ github.event.inputs.version }}" -D Arch="x64" Installer/setup.nsi
      - name: Compress Installer
        run: |
          echo "Size:"
          echo ((Get-Item Installer/ccon-v${{ github.event.inputs.version }}-win-x64-setup.exe).length)
          upx -9 Installer/ccon-v${{ github.event.inputs.version }}-win-x64-setup.exe
          echo "Size after upx:"
          echo ((Get-Item Installer/ccon-v${{ github.event.inputs.version }}-win-x64-setup.exe).length)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ccon-v${{ github.event.inputs.version }}-win-x64-setup.exe
          path: Installer/ccon-v${{ github.event.inputs.version }}-win-x64-setup.exe

  win32_build:
    name: Build x86 Installer
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install upx
      - name: Build
        run: |
          cmake . -S. -B _build -A Win32 -G "Visual Studio 16 2019"
          cmake --build _build --config Release
      - name: Compress Binaries
        run: |
          echo "Size:"
          echo ((Get-Item _build/Release/ccon.exe).length)
          upx -9 _build/Release/ccon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/Release/ccon.exe).length)
      - name: Build Installer
        run: |
          makensis -D VERSION="$ {{ github.event.inputs.version }}" -D Arch="x86" Installer/setup.nsi
      - name: Compress Installer
        run: |
          echo "Size:"
          echo ((Get-Item Installer/ccon-v${{ github.event.inputs.version }}-win-x86-setup.exe).length)
          upx -9 Installer/ccon-v${{ github.event.inputs.version }}-win-x86-setup.exe
          echo "Size after upx:"
          echo ((Get-Item Installer/ccon-v${{ github.event.inputs.version }}-win-x86-setup.exe).length)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ccon-v${{ github.event.inputs.version }}-win-x86-setup.exe
          path: Installer/ccon-v${{ github.event.inputs.version }}-win-x86-setup.exe
