name: GCC build

on:
  workflow_dispatch:

jobs:
  gcc_build:
    name: GCC Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install upx
      - name: Build
        run: |
          cmake -S. -B _build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build _build
      - name: Compress
        run: |
          echo "Size:"
          echo ((Get-Item _build/Release/ccon.exe).length)
          upx -9 _build/Release/ccon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/Release/ccon.exe).length)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ccon.exe
          path: _build/Release/ccon
